<a href="https://colab.research.google.com/github/pmaniraj55/MyWork/blob/MachineLearning/Autograd_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Autograd (compute gradient)

import torch
x=torch.tensor(2.0)
x.requires_grad,x.is_leaf

(False, True)

In [ ]:
y=3*torch.sigmoid(x)+5
y.requires_grad,y.is_leaf

(True, False)

In [ ]:
import torch
x = torch.tensor(2.0, requires_grad=True)
x.requires_grad,x.is_leaf

y=3*torch.sigmoid(x)+5

print(y)
y.requires_grad,y.is_leaf

print(x.grad)
print(x.grad_fn)
print(y.grad_fn)

y.backward()
print(x.grad) #dy/dx

tensor(7.6424, grad_fn=<AddBackward0>)
None
None
tensor(0.3150)


In [ ]:
#Gradient gets accumulated
#x.grad.zero_()
print(x.grad)

y=3*torch.sigmoid(x)+5
y.backward()
x.grad

tensor(0.3150)


tensor(0.6300)

In [ ]:
a=torch.rand(2,5,requires_grad=True)
print(a)

b=a*a+a+5
print(b)

c=b.mean()
print(c)

print(a.is_leaf,b.is_leaf,c.is_leaf)

b.retain_grad() #otherwise issue will come in b.grad
print("Before gradient computation a is:", a.grad)
c.backward()
print("After gradient computation a is:", a.grad)

print(b.grad)

tensor([[0.8967, 0.4632, 0.1277, 0.1363, 0.9521],
        [0.0591, 0.5833, 0.6169, 0.5889, 0.3918]], requires_grad=True)
tensor([[6.7007, 5.6778, 5.1440, 5.1549, 6.8587],
        [5.0626, 5.9236, 5.9975, 5.9357, 5.5453]], grad_fn=<AddBackward0>)
tensor(5.8001, grad_fn=<MeanBackward0>)
True False False
Before gradient computation a is: None
After gradient computation a is: tensor([[0.2793, 0.1926, 0.1255, 0.1273, 0.2904],
        [0.1118, 0.2167, 0.2234, 0.2178, 0.1784]])
tensor([[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000]])
